// <auto-generated />
using BireCokOrnek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BireCokOrnek.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BireCokOrnek.Data.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Calisanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ali",
                            DepartmanId = 1,
                            Soyad = "Öz"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Can",
                            DepartmanId = 2,
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Cem",
                            DepartmanId = 2,
                            Soyad = "Kaya"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ece",
                            DepartmanId = 3,
                            Soyad = "Şahin"
                        });
                });

            modelBuilder.Entity("BireCokOrnek.Data.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Muhasebe"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bilgi İşlem"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Satış ve Pazarlama"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ar-Ge"
                        });
                });

            modelBuilder.Entity("BireCokOrnek.Data.Calisan", b =>
                {
                    b.HasOne("BireCokOrnek.Data.Departman", "Departman")
                        .WithMany("Calisanlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("BireCokOrnek.Data.Departman", b =>
                {
                    b.Navigation("Calisanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
